const assert = require('node:assert/strict');
const fs = require('node:fs');

const main = fs.readFileSync('desktop/main.cjs', 'utf8');
const sqlite = fs.readFileSync('desktop/sqlite-store.cjs', 'utf8');
const preload = fs.readFileSync('desktop/preload.cjs', 'utf8');
const pkg = JSON.parse(fs.readFileSync('desktop/package.json', 'utf8'));

assert.equal(pkg.productName, '学工智伴');
assert.match(main, /contextIsolation:\s*true/);
assert.match(main, /sandbox:\s*true/);
assert.match(main, /nodeIntegration:\s*false/);
assert.match(main, /setWindowOpenHandler/);
assert.match(main, /will-navigate/);
assert.doesNotMatch(preload, /contextBridge\.exposeInMainWorld\(['"]require/);
assert.match(preload, /cwbDesktop/);
assert.match(preload, /saveBackup/);
assert.match(preload, /repositoryList/);
assert.match(preload, /setBackupSecret/);
assert.match(preload, /pruneBackups/);
assert.match(preload, /getLicenseState/);
assert.match(preload, /setLicenseState/);
assert.match(preload, /deleteLicenseState/);
assert.match(preload, /updateStatus/);
assert.match(preload, /updateCheck/);
assert.match(preload, /updateDownload/);
assert.match(preload, /updateInstall/);
assert.match(preload, /updateCancel/);
assert.match(preload, /onUpdateState/);
assert.match(sqlite, /node:sqlite/);
assert.match(main, /desktop:repository-put/);
assert.match(main, /ALLOWED_COLLECTIONS/);
assert.match(main, /validateCollection/);
assert.match(main, /validateCollection\(collection\)/);
assert.match(main, /validateAttachmentId/);
assert.match(main, /ATTACHMENT_SIZE_LIMIT/);
assert.match(main, /desktop:write-attachment/);
assert.match(main, /encryptBuffer/);
assert.match(main, /migrateLegacyDesktopData/);
assert.match(main, /CWB_DESKTOP_SMOKE/);
assert.match(main, /loadOrCreateVaultKey/, 'desktop must use the versioned vault key loader');
assert.match(main, /allowSmoke:Boolean\(process\.env\.CWB_DESKTOP_SMOKE\)/, 'only the isolated smoke protocol may use a non-system vault key');
assert.match(main, /VAULT_KEY_DECRYPT_FAILED|vault\.cjs/, 'desktop must expose diagnosable vault errors');
assert.match(main, /app\.setName\(APP_IDENTITY\)/);
assert.match(main, /const \{[^}]*\bMenu\b[^}]*\} = require\('electron'\)/, 'desktop main process must load Electron Menu to control the Windows application menu');
assert.match(main, /if \(process\.platform === 'win32'\) \{\s*Menu\.setApplicationMenu\(null\);\s*mainWindow\.setMenuBarVisibility\(false\);\s*\}/, 'Windows desktop must hide the built-in File/Edit/View menu rather than expose an unused top menu bar');
assert.match(preload, /readAttachment/);
assert.match(preload, /chooseBackupFolder/);
assert.match(main, /extensions: \['cwbk'\]/, 'desktop backup picker must not present exchange JSON as an encrypted backup');
assert.match(preload, /exportRecoveryKit/);
assert.match(preload, /restoreRecoveryKit/);
assert.match(main, /atomicWriteFile\(target, serialized\)/, 'desktop backups must use the shared atomic writer');
assert.match(main, /DATA_MIGRATION_ATTACHMENT_CORRUPTED/, 'data migration must validate encrypted attachments before activation');
assert.match(main, /ATTACHMENT_DECRYPT_FAILED/, 'recovery must validate attachments with the recovered key');
assert.match(preload, /lanSyncStart/);
assert.match(preload, /lanSyncPairingQr/);
assert.match(preload, /lanSyncConfirmPairing/);
assert.match(preload, /lanSyncPauseDevice/);
assert.match(preload, /lanSyncResumeDevice/);
assert.match(main, /desktop:migrate-data-folder/);
assert.match(main, /createLanSyncHost/);
assert.match(main, /desktop:lan-sync-pairing-qr/);
assert.match(main, /createPairingQrPayload/);
assert.match(main, /require\('qrcode'\)/);
assert.match(main, /desktop:get-license-state/);
assert.match(main, /safeStorage\.encryptString/);
assert.match(main, /desktop:update-check/);
assert.match(main, /createElectronUpdateRuntime/);
console.log('PASS electron-surface');
