const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const licenseCore = require('../src/core/cwb-license.js');
const redemption = require('../services/license-server/redemption-code.cjs');
const { createSigner } = require('../services/license-server/service.cjs');
const { createCommercialService } = require('../services/license-server/production.cjs');
const { createCommercialMemoryStore } = require('./license-server-fixture.js');

(async () => {
  const { privateKey } = crypto.generateKeyPairSync('ed25519');
  const signer = createSigner({ privateKey, kid:'redemption-contract' });
  const store = createCommercialMemoryStore();
  const generated = redemption.generate();
  const aiGenerated = redemption.generate();
  const wrongProductGenerated = redemption.generate();
  const campaign = redemption.normalizeCampaign({ campaign_id:'contract-campaign', plan:'standard_perpetual', code_hash:generated.code_hash, status:'active' });
  const aiCampaign = redemption.normalizeCampaign({ campaign_id:'contract-ai-campaign', plan:'ai_perpetual', code_hash:aiGenerated.code_hash, status:'active' });
  const wrongProductCampaign = redemption.normalizeCampaign({ campaign_id:'contract-wrong-product', product_id:'another-product', plan:'standard_perpetual', code_hash:wrongProductGenerated.code_hash, status:'active' });
  await store.upsertRedemptionCampaign({ ...campaign, product_id:licenseCore.PRODUCT_ID });
  await store.upsertRedemptionCampaign({ ...aiCampaign, product_id:licenseCore.PRODUCT_ID });
  await store.upsertRedemptionCampaign(wrongProductCampaign);
  const service = createCommercialService({ store, signer, orderAccessSecret:'redemption-secret', publicKeys:{ [signer.kid]:signer.publicKey }, redemptionCampaigns:[campaign, aiCampaign] });
  const first = await service.redeem({ code:generated.code, workspace_id:'redeem-w1', device_id:'redeem-d1' });
  assert.equal(first.payload.plan, 'standard_perpetual');
  assert.equal(first.payload.ai, false);
  assert.match(first.token, /^CWB-LIC-1\./);
  assert.equal((await store.listDevices(first.license_id)).length, 1);
  const second = await service.redeem({ code:generated.code, workspace_id:'redeem-w1', device_id:'redeem-d2' });
  assert.equal(second.license_id, first.license_id, 'same workspace must reuse its issued license');
  assert.equal((await store.listDevices(first.license_id)).length, 2);
  const third = await service.redeem({ code:generated.code, workspace_id:'redeem-w2', device_id:'redeem-d3' });
  assert.notEqual(third.license_id, first.license_id, 'different workspaces must receive independent licenses');
  const ai = await service.redeem({ code:aiGenerated.code, workspace_id:'redeem-ai-w1', device_id:'redeem-ai-d1' });
  assert.equal(ai.payload.plan, 'ai_perpetual', 'the second long-lived campaign must issue the AI perpetual tier');
  assert.equal(ai.payload.ai, true);
  assert.equal(ai.payload.perpetual_updates, true);
  await assert.rejects(() => service.redeem({ code:wrongProductGenerated.code, workspace_id:'redeem-wrong-product', device_id:'redeem-d5' }), error => error.code === 'REDEMPTION_PLAN_INVALID');
  assert.throws(() => redemption.parse('CWB-REDEEM-1.not-a-real-code'), error => error.code === 'REDEMPTION_CODE_INVALID');
  await assert.rejects(() => service.redeem({ code:'CWB-REDEEM-1.' + 'x'.repeat(43), workspace_id:'redeem-w3', device_id:'redeem-d4' }), error => error.code === 'REDEMPTION_CODE_INVALID');
  console.log('PASS redemption-service');
})().catch(error => { console.error(error.stack || error.message); process.exit(1); });
